### PR TITLE
Track invalid values by exceptions and types

### LINKED ISSUE #10: Types - invalid value tracking
Types are representation of whole VO structure and are also able to track exact keys which are invalid. In order to check which keys were invalid, user has to compare invalid keys with sent data and that's impractical.

All the Type methods which mark value invalid should be required to also add that value to Type so it could be rendered together with invalid key by Formatter.

In this stage we should resolve the problem to satisfaction just in `Type`. Optimal rendering in `ErrorFormatter` could be quite complex and for now only minimal implementation in `VisualErrorFormatter` should be enough to verify solution - something like `key: string (received int(123) instead)`

### PR DESCRIPTION
**Pull request by mrceperka**
Closes #10

### CODE REVIEW

File: src/Processing/DefaultProcessor.php [hunk 1]
```diff
@@ -691,12 +698,14 @@ public function processSkippedProperties(
 				$object->$propertyName = $processed;
 				$skippedPropertiesContext->removeInitializedProperty($propertyName);
 			} catch (ValueDoesNotMatch | InvalidData $exception) {
-				$type->overwriteInvalidField($fieldName, $exception->getInvalidType());
+				$type->overwriteInvalidField($fieldName, $exception);
+				// TODO: better throw early?
```
Comment (mabar) [inline src/Processing/DefaultProcessor.php]: All of the fields are supposed to be processed at the same time, it's correct

File: src/Processing/DefaultProcessor.php [hunk 2]
```diff
@@ -691,12 +698,14 @@ public function processSkippedProperties(
...
 			}
 		}
 
 		// If any of fields is invalid, throw error
 		if ($type->hasInvalidFields()) {
+			// TODO: Where to get value?
 			throw InvalidData::create($type);
```
Comment (mabar) [inline src/Processing/DefaultProcessor.php]: I guess it's case for NoValue. Invalid values are already tracked by individual invalid fields

File: src/Rules/AllOfRule.php [hunk 3]
```diff
@@ -39,13 +39,13 @@ public function processValue($value, Args $args, FieldContext $context)
...
 			} catch (ValueDoesNotMatch | InvalidData $exception) {
-				$type->overwriteInvalidSubtype($key, $exception->getInvalidType());
+				$type->overwriteInvalidSubtype($key, $exception);
 				$anyValidationFailed = true;
 			}
 		}
 
 		if ($anyValidationFailed) {
-			throw ValueDoesNotMatch::create($type);
+			throw ValueDoesNotMatch::create($type, $value);
```
Comment (mabar) [inline src/Rules/AllOfRule.php]: $value may be already mutated here, original value from function input should be added. Test for that case is welcome

File: src/Rules/AnyOfRule.php [hunk 4]
```diff
@@ -40,12 +40,12 @@ public function processValue($value, Args $args, FieldContext $context)
...
 				$anyValidationSucceeded = true;
 			} catch (ValueDoesNotMatch | InvalidData $exception) {
-				$type->overwriteInvalidSubtype($key, $exception->getInvalidType());
+				$type->overwriteInvalidSubtype($key, $exception);
 			}
 		}
 
 		if (!$anyValidationSucceeded) {
-			throw ValueDoesNotMatch::create($type);
+			throw ValueDoesNotMatch::create($type, $value);
```
Comment (mabar) [inline src/Rules/AnyOfRule.php]: Same test as for AllOfRule is welcome. Mutation of value shouldn't matter in this case but let's be future self proof

File: src/Rules/ArrayOfRule.php [hunk 5]
```diff
@@ -90,7 +90,7 @@ public function processValue($value, Args $args, FieldContext $context): array
 		if ($args->maxItems !== null && count($value) > $args->maxItems) {
 			$type->markParameterInvalid(self::MAX_ITEMS);
 
-			throw ValueDoesNotMatch::create($type);
+			throw ValueDoesNotMatch::create($type, $value);
```
Comment (mabar) [inline src/Rules/ArrayOfRule.php:94]: We should find a way how to reduce that value, we want to drop values above limit as soon as the processing is finished to save memory. It does not really matter anyway what the specific values were, just the fact they are above limit.

Comment (mabar) [reply src/Rules/ArrayOfRule.php:94]: Using reduced reference to value may be helpful anyway. e.g. for string with max length 100 is enough to have like 10 characters string with information that given string had 10k characters, no way we would dump it whole in error formatter

File: src/Types/ArrayType.php [hunk 6]
```diff
@@ -29,14 +30,14 @@ public function getKeyType(): ?Type
...
+	public function addInvalidPair($key, ?WithTypeAndValue $keyTypeAndValue, ?WithTypeAndValue $itemTypeAndValue): void
 	{
-		if ($keyType === null && $itemType === null) {
+		if ($keyTypeAndValue === null && $itemTypeAndValue === null) {
 			throw InvalidArgument::create()
 				->withMessage('At least one of key type and item type of invalid pair should not be null');
 		}
 
-		$this->invalidPairs[$key] = [$keyType, $itemType];
+		$this->invalidPairs[$key] = [$keyTypeAndValue !== null ? $keyTypeAndValue->getInvalidType() : null, $itemTypeAndValue !== null ? $itemTypeAndValue->getInvalidType() : null];
```
Comment (mabar) [inline src/Types/ArrayType.php]: `WithTypeAndValue` should be stored in invalidPairs instead of getting `Type` here

File: src/Types/CompoundType.php [hunk 7]
```diff
@@ -128,7 +129,7 @@ public function overwriteInvalidSubtype($key, Type $type): void
 				));
 		}
 
-		$this->subtypes[$key] = $type;
+		$this->subtypes[$key] = $exception->getInvalidType();
```
Comment (mabar) [inline src/Types/CompoundType.php]: `WithTypeAndValue` should be stored in subtypes instead of getting `Type` here

File: src/Types/CompoundType.php [hunk 8]
```diff
@@ -110,7 +111,7 @@ public function isSubtypeSkipped($key): bool
 	/**
 	 * @param string|int $key
 	 */
-	public function overwriteInvalidSubtype($key, Type $type): void
+	public function overwriteInvalidSubtype($key, WithTypeAndValue $exception): void
```
Comment (mabar) [inline src/Types/CompoundType.php]: `CompoundType` should probably change interface, for each subtype is value gonna be the same

File: src/Types/ListType.php [hunk 9]
```diff
@@ -23,9 +25,9 @@ public function areKeysInvalid(): bool
 	/**
 	 * @param string|int $key
 	 */
-	public function addInvalidItem($key, Type $itemType): void
+	public function addInvalidItem($key, WithTypeAndValue $typeAndValue): void
 	{
-		$this->invalidItems[$key] = $itemType;
+		$this->invalidItems[$key] = $typeAndValue->getInvalidType();
```
Comment (mabar) [inline src/Types/ListType.php]: `WithTypeAndValue` should be stored in invalidItems instead of getting `Type` here

File: src/Types/StructureType.php [hunk 10]
```diff
@@ -48,9 +49,9 @@ public function addField($field, Type $type): void
 	/**
 	 * @param int|string $field
 	 */
-	public function overwriteInvalidField($field, Type $type): void
+	public function overwriteInvalidField($field, WithTypeAndValue $typeAndValue): void
 	{
-		$this->fields[$field] = $type;
+		$this->fields[$field] = $typeAndValue->getInvalidType();
```
Comment (mabar) [inline src/Types/StructureType.php:54]: `WithTypeAndValue` should be stored in fields instead of getting `Type` here

File: src/Exception/WithTypeAndValue.php [hunk 11]
```diff
@@ -0,0 +1,17 @@
+<?php declare(strict_types = 1);
+
+namespace Orisai\ObjectMapper\Exception;
+
+use Orisai\ObjectMapper\Types\Type;
+
+interface WithTypeAndValue
```
Comment (mabar) [inline src/Exception/WithTypeAndValue.php]: `extends CheckedException`
Should ideally be marked as `@sealed` but well, that is still an unknown concept for PHP

File: src/Processing/DefaultProcessor.php [hunk 12]
```diff
@@ -279,7 +280,10 @@ protected function handleSentFields(
 				$hint = ($hintedFieldName !== null ? sprintf(', did you mean `%s`?', $hintedFieldName) : '.');
 				$type->overwriteInvalidField(
 					$fieldName,
-					new MessageType(sprintf('Field is unknown%s', $hint)),
+					ValueDoesNotMatch::create(
+						new MessageType(sprintf('Field is unknown%s', $hint)),
+						NoValue::create(),
```
Comment (mabar) [inline src/Processing/DefaultProcessor.php]: `$value` should be available here

File: src/NoValue.php [hunk 13]
```diff
@@ -0,0 +1,18 @@
...
+
+namespace Orisai\ObjectMapper;
+
+final class NoValue
+{
+
+	private function __construct()
+	{
+
+	}
```
Comment (mabar) [inline src/NoValue.php]: `// Represents a completely missing value`

File: src/Processing/DefaultProcessor.php [hunk 14]
```diff
@@ -395,17 +399,20 @@ protected function handleMissingFields(
...
 					$missingField,
-					$propertyRule->createType(
-						$this->createRuleArgsInst($propertyRule, $propertyRuleMeta),
-						$this->getTypeContext(),
+					ValueDoesNotMatch::create(
+						$propertyRule->createType(
+							$this->createRuleArgsInst($propertyRule, $propertyRuleMeta),
+							$this->getTypeContext(),
+						),
+						$data,
```
Comment (mabar) [inline src/Processing/DefaultProcessor.php]: `$data` is for whole VO, nut just for one field. This is the case for `new NoValue`

File: src/Processing/DefaultProcessor.php [hunk 15]
```diff
@@ -226,16 +227,16 @@ protected function handleFields(
...
-		$data = $this->handleSentFields($data, $fieldSetContext, $runContext);
-		$data = $this->handleMissingFields($data, $fieldSetContext, $runContext);
+		$handledData = $this->handleSentFields($data, $fieldSetContext, $runContext);
+		$handledData = $this->handleMissingFields($handledData, $fieldSetContext, $runContext);
 
 		$type = $fieldSetContext->getType();
 
 		if ($type->hasInvalidFields()) {
-			throw InvalidData::create($type);
+			throw InvalidData::create($type, $data);
```
Comment (mabar) [inline src/Processing/DefaultProcessor.php]: `NoValue`, invalid data are in invalid fields already

File: src/Processing/DefaultProcessor.php [hunk 16]
```diff
@@ -527,7 +534,7 @@ protected function handleClassCallbacks(
 				$type->addError($catchedType);
 			}
 
-			throw InvalidData::create($type);
+			throw InvalidData::create($type, $data);
```
Comment (mabar) [inline src/Processing/DefaultProcessor.php:542]: I think there should also be `NoValue` in case `$catchedType === $type` because user is supposed to add error to original type himself, but I have to find out myself

File: src/Types/StructureType.php (hunk 10 above)
Comment (mrceperka) [reply src/Types/StructureType.php:54]: Hm, that's gonna break something. For example `addField` would have to accept `WithTypeAndValue` as well. Or we could wrap it.

Comment (mabar) [reply src/Types/StructureType.php:54]: Imho we have to change api for obtaining errors from types anyway. Current one counts only with types, not values.

File: src/Rules/AllOfRule.php (hunk 3 above)
Comment (mrceperka) [reply src/Rules/AllOfRule.php]: TODO: test case

File: src/Types/StructureType.php (hunk 10 above)
Comment (mabar) [reply src/Types/StructureType.php:54]: So no changing of `addField`,  errors will be stored separately from origina types

File: src/Rules/AnyOfRule.php (hunk 4 above)
Comment (mrceperka) [reply src/Rules/AnyOfRule.php]: TODO: test case

File: src/Rules/ArrayOfRule.php (hunk 5 above)
Comment (mrceperka) [reply src/Rules/ArrayOfRule.php:94]: We should pass whole value to stay consistent.
Other services may manipulate it as they need.

Or maybe add an extra arg which would tell if values above limit should be dropped?
But then we would have to slice that array and that's not for free either :/

Comment (mabar) [reply src/Rules/ArrayOfRule.php:94]: Don't solve it now, it's more a note for me :) I just want to be sure we don't create some memory bottleneck

File: src/NoValue.php [hunk 17]
```diff
@@ -5,6 +5,9 @@
 final class NoValue
 {
 
+	/**
+	 * Represents a completely missing value
+	 */
```
Comment (mabar) [inline src/NoValue.php]: I meant for the function body, to make coding standard happy

File: src/Rules/AnyOfRule.php [hunk 18]
```diff
@@ -12,13 +12,14 @@ final class AnyOfRule extends CompoundRule
...
 	/**
-	 * @param mixed $value
+	 * @param mixed            $value
 	 * @param CompoundRuleArgs $args
 	 * @return mixed
 	 * @throws ValueDoesNotMatch
 	 */
 	public function processValue($value, Args $args, FieldContext $context)
 	{
+		$inputValue = $value;
```
Comment (mabar) [inline src/Rules/AnyOfRule.php]: It shouldn't be needed here, it just needs to be tested

File: src/Types/StructureType.php (hunk 10 above)
Comment (mrceperka) [reply src/Types/StructureType.php:54]: Oke, fine :)

File: src/NoValue.php (hunk 17 above)
Comment (mrceperka) [reply src/NoValue.php]: Yeah, should be ok now :D

File: src/Types/StructureType.php (hunk 10 above)
Comment (mrceperka) [reply src/Types/StructureType.php:54]: `addError` should probably change as well.

File: src/Types/CompoundType.php (hunk 8 above)
Comment (mrceperka) [reply src/Types/CompoundType.php]: Change how? Tell me plx :D

File: src/Rules/AnyOfRule.php (hunk 18 above)
Comment (mrceperka) [reply src/Rules/AnyOfRule.php]: TODO: test case

File: src/Types/StructureType.php (hunk 10 above)
Comment (mabar) [reply src/Types/StructureType.php:54]: Yup. It's just special case for callbacks, should have exception available too

File: src/Types/CompoundType.php (hunk 8 above)
Comment (mabar) [reply src/Types/CompoundType.php]: `setInvalidSubtypes(string|int $key, array<Type> $types, mixed $value)`
Bit inconsistent with other invalidation apis, but passing value with each Type really dost not make sense here

File: src/Rules/ListOfRule.php [hunk 19]
```diff
@@ -100,12 +100,12 @@ public function processValue($value, Args $args, FieldContext $context): array
...
 			} catch (ValueDoesNotMatch | InvalidData $exception) {
 				//TODO - mark key invalid (if not just one higher than previous or if it's first and not 0)
-				$type->addInvalidItem($key, $exception->getInvalidType());
+				$type->addInvalidItem($key, $exception);
 			}
 		}
 
 		if ($type->hasInvalidParameters() || $type->hasInvalidItems()) {
-			throw ValueDoesNotMatch::create($type);
+			throw ValueDoesNotMatch::create($type, $value);
```
Comment (mabar) [inline src/Rules/ListOfRule.php]: In case only items are invalid there is no need to track whole value
```php
		if (($invalidParams = $type->hasInvalidParameters()) || $type->hasInvalidItems()) {
			throw ValueDoesNotMatch::create(
				$type,
				!$invalidParams ? NoValue::create() : $value,
			);
		}
```

Comment (mabar) [reply src/Rules/ListOfRule.php]: //TODO - test case

File: src/Rules/ArrayOfRule.php [hunk 20]
```diff
@@ -129,16 +129,12 @@ public function processValue($value, Args $args, FieldContext $context): array
...
-					$itemException !== null ? $itemException->getInvalidType() : null,
-				);
+				$type->addInvalidPair($key, $keyException, $itemException);
 			}
 		}
 
 		if ($type->hasInvalidParameters() || $type->hasInvalidPairs()) {
-			throw ValueDoesNotMatch::create($type);
+			throw ValueDoesNotMatch::create($type, $value);
 		}
```
Comment (mabar) [inline src/Rules/ArrayOfRule.php]: In case only pairs are invalid there is no need to track whole value
```php
		if (($invalidParams = $type->hasInvalidParameters()) || $type->hasInvalidPairs()) {
			throw ValueDoesNotMatch::create(
				$type,
				!$invalidParams ? NoValue::create() : $value,
			);
		}
```

Comment (mabar) [reply src/Rules/ArrayOfRule.php]: TODO - test case

File: src/Types/StructureType.php [hunk 21]
```diff
@@ -48,10 +49,10 @@ public function addField($field, Type $type): void
 	/**
 	 * @param int|string $field
 	 */
-	public function overwriteInvalidField($field, Type $type): void
+	public function overwriteInvalidField($field, WithTypeAndValue $typeAndValue): void
 	{
-		$this->fields[$field] = $type;
-		$this->invalidFields[$field] = true;
+		$this->fields[$field] = $typeAndValue->getInvalidType();
```
Comment (mabar) [inline src/Types/StructureType.php:54]: Change name to `setInvalidField` and drop the override of fields please. It's not needed anymore, formatter can use getInvalidFields() instead

Comment (mrceperka) [reply src/Types/StructureType.php:54]: We will have to figure out how to merge `fields` and `invalidField`. Because formatter needs both.
https://github.com/orisai/object-mapper/blob/c5a9db548383d59baae8b9b77a0f64a3299c2f41/src/Formatting/VisualErrorFormatter.php#L229-L244

File: src/Types/CompoundType.php (hunk 8 above)
Comment (mrceperka) [reply src/Types/CompoundType.php]: So... rename `overwriteInvalidSubtype` to `setInvalidSubtypes`? And stop overwriting fields? (same as for `StructureType`)

File: src/Types/StructureType.php (hunk 21 above)
Comment (mabar) [reply src/Types/StructureType.php:54]: Just prefer invalid, if they exist. If all should be rendered, merge the arrays (prioritize the invalid), keys are field names.

File: src/Types/CompoundType.php (hunk 8 above)
Comment (mabar) [reply src/Types/CompoundType.php]: And set them all with single method call. The $key paramter should be moved to $types probably as well, I forgot the first time

File: src/Rules/AllOfRule.php (hunk 3 above)
Comment (mrceperka) [reply src/Rules/AllOfRule.php]: Test case added

File: src/Rules/AnyOfRule.php (hunk 18 above)
Comment (mrceperka) [reply src/Rules/AnyOfRule.php]: Test case added.

File: src/Rules/AnyOfRule.php (hunk 4 above)
Comment (mrceperka) [reply src/Rules/AnyOfRule.php]: Test case added

File: src/Types/StructureType.php (hunk 21 above)
Comment (mrceperka) [reply src/Types/StructureType.php:54]: I'd say that `filterFields` should return `array<WithTypeAndValue>` insted of `array<Type>`. 
I am not able to get the value of `field` (cos it's `Type`), cos they are not tracked. Values are tracked only for `invalidFields`.
